chinese version of README.md
SCA-OAU/LearnLink pull request #10
Opened 2024-10-16 03:47 UTC by hxGkyle

2024-10-17 02:43 UTC, Charity10 requested changes

2024-10-17 02:43 UTC, Charity10 commented on docs/README.zh.md
> +3. [个人发展 (Personal Development)](#-personal-development)
There should be a slight change in the links. None of the links in the Chinese version are working correctly; most lead to 404 error page.

Try figuring it out yourself and please feel free to reach out if you want my help. 
ps: I don't want to spoon-feed the corrections to you.😉

2024-10-17 02:43 UTC, Charity10 commented on docs/README.zh.md
> +- [**初级 (Beginner Level)**](./FrontendDevelopment/Frontend.md/#-beginner-level)
same with the links here and also in other sections too

2024-10-17 05:59 UTC, hxGkyle commented
solved. 
let me know if there needs any extra help

2024-10-18 01:22 UTC, Charity10 commented
This is good to go👏
but will you be updating the Chinese readme version cos the original Readme will keep on changing as new resources are added

2024-10-20 23:37 UTC, hxGkyle commented
i could sync it around per mouth, when i see there is a change. 
and can u merge the request? i'm doing it for school project and it's about to due

2024-10-21 08:22 UTC, Charity10 commented
> i could sync it around per mouth, when i see there is a change. and can u merge the request? i'm doing it for school project and it's about to due

I will merge it.
The note in the Chinese version said the doc was translated in 2014/10/20 
was that on purpose?
if it wasn't you can change it and send another pull request

2024-10-21 08:25 UTC, merged

2024-10-21 17:00 UTC, hxGkyle commented
> > i could sync it around per mouth, when i see there is a change. and can u merge the request? i'm doing it for school project and it's about to due
> 
> I will merge it. The note in the Chinese version said the doc was translated in 2014/10/20 was that on purpose? if it wasn't you can change it and send another pull request

it is, just in case someone didn't notice the version difference