created fullstack development folder
SCA-OAU/LearnLink pull request #2
Opened 2024-10-09 16:47 UTC by Rachel-Cellulose

**Add Fullstack Development Resources Folder**

Description: This pull request adds a new folder named fullstack-development, intended to serve as a dedicated space for resources aimed at helping learners navigate the full-stack development landscape.

Key Changes:
Created a new directory: fullstack-development.

Impact:
This contribution lays the foundation for future enhancements by providing a structured location for resources related to full-stack development. As resources are added, this folder will become a valuable tool for individuals seeking structured materials to enhance their full-stack development skills.

2024-10-11 02:25 UTC, Charity10 requested changes

2024-10-14 23:36 UTC, Rachel-Cellulose commented on FullstackDevelopment/Fullstack.md
Thank you. Changes have been updated.

2024-10-16 11:51 UTC, Charity10 commented on FullstackDevelopment/Fullstack.md
> +1. [🚀 Getting Started with Fullstack Development](#-getting-started-with-fullstack-development)
@Rachel-Cellulose 
Your project is good

The only problem now is if I click on the table of contents it doesn't take me to that section instead I'm directed to a new page entirely

And this page looks like a web page with just html and no CSS

You can look at the readme file to see the difference

2024-10-17 02:24 UTC, Charity10 commented on FullstackDevelopment/Fullstack.md
> +We welcome contributions to help improve these resources! If you have more fullstack development resources, tutorials, or suggestions, please follow our [contribution guidelines](#) to make your addi
Link the contribution.md file here

Pull first to get updated changes from the repo

2024-10-17 02:25 UTC, Charity10 commented on FullstackDevelopment/Fullstack.md
> +We welcome contributions to help improve these resources! If you have more fullstack development resources, tutorials, or suggestions, please follow our [contribution guidelines](#) to make your addi
> Link the contribution.md file here
> 
> Pull first to get updated changes from the repo


@Rachel-Cellulose

2024-10-20 02:54 UTC, merged