Add the technical writing resources
SCA-OAU/LearnLink pull request #24
Opened 2024-10-25 19:43 UTC by motuncoded

This commit introduces the technical resources section

2024-10-26 01:48 UTC, Charity10 commented on TechnicalWriting/TechicalWriting.md
> +![](./assets/Hashnode.png)
Add the hashnode text here

2024-10-26 01:50 UTC, Charity10 requested changes
Please update the readme file.

2024-10-26 03:29 UTC, motuncoded commented
Would be glad to do that

2024-10-28 12:43 UTC, Charity10 commented on README.md
> +
No 5 and 7 links not working
For no 5  just pull from the master to get the updated version, Arafat already fixed that

2024-10-28 12:47 UTC, motuncoded commented
Ok

2024-11-07 10:28 UTC, merged